# Nord theme for glow
style: "nord.json"

# show local files only; no network (TUI-mode only)
local: false

# mouse support (TUI-mode only)
mouse: true

# use pager to display markdown
pager: false

# word-wrap at width
width: 100
